"""empty message

Revision ID: 617cf61c6ef1
Revises: 
Create Date: 2017-10-15 20:03:01.698613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617cf61c6ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_key')
    # ### end Alembic commands ###
